version: "3.8"
services:
  appban:
    container_name: appban
    image: latest123/stable
    restart: always
    build: .
    ports:
       - 7861:7860
    links:
      - login-app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  login-app:
    container_name: whatsapp
    image: latest123/whatsapp
    restart: always
    build: .
    links:
      - mongo
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    expose:
      - 27017
    volumes:
      - ./mongo_data:/data/db
